name: Test and Deploy
on:
  push:
    branches: [master]
  pull_request:

jobs:
  testAndBuild:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - name: Istall deps
        run: npm install

      - name: Run test
        run: npm run test

      - name: Run build
        run: npm run build

      - name: Cache build
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: build-folder
          path: dist

  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    needs: [testAndBuild]
    name: Deploy on Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Restore cache
        uses: actions/download-artifact@v2
        with:
          name: build-folder
          path: build

      - name: SSH Deploy
        if: ${{ github.event_name != 'pull_request' }}
        uses: easingthemes/ssh-deploy@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.SERVER_FOLDER }}
          SOURCE: build
          ARGS: -av --delete
